### PR TITLE
Delegation Component updates and fixes

### LINKED ISSUE #130: `tokenBalance` in `useTokenData` is a `Number` but should be a `BigNumber`
Should go without saying -- no casting BigNumbers to Numbers when the data is "untrusted" (i.e. any random token).

Just return the BigNumber back into the data layer and let the view layer handle how to display it (we're returning back `decimals` too, so ethers.js can easily handle displaying it as a formatted string)

### LINKED ISSUE #154: Delegate Vote component should show how much weight is delegated to connected account

### PR DESCRIPTION
**Pull request by adamgall**
Closes #130
Closes #154 

Screen Shot 2022-05-04 at 3 33 58 PM

Changes include:

- Expose user token balance as a `BigNumber`, UI layer converts to human-readable string
- Remove full screen "transaction pending" modal from Delegate screen when transaction is in progress
  - rely on the toast to show outstanding transaction information
  - disable the Delegate button while transaction is outstanding
- add yellow bar to bottom of all "outstanding transaction" toasts
- after successful delegation transaction, clear out the Delegate address input box
- Add at-load and realtime-listener data fetching for getting the current account's voting weight (how much voting weight has been delegated to them), expose in `tokenData`
- Display the current account's voting weight on the Delegate page
- clean up the `useDelegateVote` hook a lot

### CODE REVIEW

File: src/components/DAOs/DAO/Delegate.tsx [hunk 1]
```diff
@@ -33,14 +30,33 @@ function Delegate() {
     setNewDelegatee(account);
   };
 
-  const delegateVote = useDelegateVote({
+  const [delegateVote, pending] = useDelegateVote({
```
Comment (adamgall) [inline src/components/DAOs/DAO/Delegate.tsx:33]: Instead of passing a function into `useDelegateVote` to set a pending state, expose a boolean from the hook up into the caller's context

File: src/components/DAOs/DAO/Delegate.tsx [hunk 2]
```diff
@@ -33,14 +30,33 @@ function Delegate() {
...
+  const [readableVotingWeight, setReadableVotingWeight] = useState<string>();
+  useEffect(() => {
+    if (votingWeight === undefined || decimals === undefined || symbol === undefined) {
+      setReadableVotingWeight(undefined);
+      return;
+    }
+
+    setReadableVotingWeight(`${utils.formatUnits(votingWeight, decimals)} ${symbol}`);
+  }, [decimals, votingWeight, symbol]);
+
```
Comment (adamgall) [inline src/components/DAOs/DAO/Delegate.tsx:57]: Created some simple state here to turn the `BigNumber` balance, `number` decimals, and `string` token symbol into single human readable strings (or `undefined` if we're still trying to build that string). This was to simplify the logic in the rendered component down below

File: src/components/DAOs/DAO/Delegate.tsx [hunk 3]
```diff
@@ -33,14 +30,33 @@ function Delegate() {
...
   return (
     <>
-      <Pending message="Delegating Vote..." pending={pending} />
```
Comment (adamgall) [inline src/components/DAOs/DAO/Delegate.tsx:43]: No longer using this full screen Pending modal...

File: src/components/DAOs/DAO/Delegate.tsx [hunk 4]
```diff
@@ -70,7 +86,13 @@ function Delegate() {
...
             </EtherscanLink>
           </div>
-          <SecondaryButton disabled={!validAddress || newDelegatee.trim() === ""} onClick={() => delegateVote()} label="Delegate" className="mt-4" />
+          <div className="flex mx-2 my-1 text-gray-50">
+            Current Voting Weight:{" "}
+            <span className="text-gray-25 ml-2">
+              <DataLoadingWrapper isLoading={readableVotingWeight === undefined}>{readableVotingWeight}</DataLoadingWrapper>
+            </span>
+          </div>
+          <SecondaryButton disabled={!validAddress || newDelegatee.trim() === "" || pending} onClick={() => delegateVote()} label="Delegate" className="mt-4" />
```
Comment (adamgall) [inline src/components/DAOs/DAO/Delegate.tsx:95]: ... instead, just keep this button disabled if the transaction is pending

File: src/components/DAOs/DAO/Delegate.tsx [hunk 5]
```diff
@@ -70,7 +86,13 @@ function Delegate() {
               </DataLoadingWrapper>
             </EtherscanLink>
           </div>
-          <SecondaryButton disabled={!validAddress || newDelegatee.trim() === ""} onClick={() => delegateVote()} label="Delegate" className="mt-4" />
+          <div className="flex mx-2 my-1 text-gray-50">
+            Current Voting Weight:{" "}
+            <span className="text-gray-25 ml-2">
+              <DataLoadingWrapper isLoading={readableVotingWeight === undefined}>{readableVotingWeight}</DataLoadingWrapper>
+            </span>
+          </div>
```
Comment (adamgall) [inline src/components/DAOs/DAO/Delegate.tsx:94]: New feature: display the user's current voting weight (sum of all of the tokens that have been delegated to them)

File: src/components/ui/loaders/DataLoadingWrapper.tsx [hunk 6]
```diff
@@ -1,8 +1,6 @@
-import { ReactElement } from "react";
-
 interface DataLoadingWrapperProps {
   isLoading: boolean;
-  children: ReactElement<any, any> | string;
+  children: React.ReactNode;
```
Comment (adamgall) [inline src/components/ui/loaders/DataLoadingWrapper.tsx:3]: Lil update to allow more types of `children`, necessary for the code in this PR

File: src/daoData/daoData.ts [hunk 7]
```diff
@@ -25,8 +26,9 @@ export interface DAOData {
     name: string | undefined,
     symbol: string | undefined,
     decimals: number | undefined
-    userBalance: number | undefined,
+    userBalance: BigNumber | undefined,
```
Comment (adamgall) [inline src/daoData/daoData.ts:29]: Export this as a BigNumber not a number. Numbers for token balances aren't safe

File: src/daoData/useDelegateVote.ts [hunk 8]
```diff
@@ -1,46 +1,32 @@
-import { useCallback, useEffect } from 'react'
+import { useCallback } from 'react'
 import { useTransaction } from '../web3/transactions';
-import { useWeb3 } from '../web3';
 import { useDAOData } from './index';
 
 const useDelegateVote = ({
   delegatee,
-  setPending,
+  successCallback,
```
Comment (adamgall) [inline src/daoData/useDelegateVote.ts:7]: As mentioned earlier, don't pass in a function to set a pending state (see on line 29 we just return a boolean).

I also wanted to allow state to get updated on successful transaction, so pass in a function to do that

File: src/daoData/useDelegateVote.ts [hunk 9]
```diff
@@ -1,46 +1,32 @@
...
-    setPending(contractCallPending);
-  }, [setPending, contractCallPending]);
 
   let delegateVote = useCallback(() => {
-    if (
-      signerOrProvider === undefined ||
-      setPending === undefined ||
-      token === undefined ||
-      delegatee === undefined
-    ) {
```
Comment (adamgall) [inline src/daoData/useDelegateVote.ts:29]: idk why all these are here, half of them weren't being used in the logic

File: src/daoData/useDelegateVote.ts [hunk 10]
```diff
@@ -1,46 +1,32 @@
...
 
     contractCallDelegateVote({
-      contractFn: () => token.delegate(delegatee),
+      contractFn: () => tokenContract.delegate(delegatee),
       pendingMessage: "Delegating Vote",
       failedMessage: "Vote Delegation Failed",
       successMessage: "Vote Delegated",
-      rpcErrorCallback: (error: any) => {
-        console.error(error)
-      },
```
Comment (adamgall) [inline src/daoData/useDelegateVote.ts:40]: Remove this, because if there is an RPC error it's already getting logged in the `useTransaction` hook. Don't need to log the error twice.

File: src/daoData/useDelegateVote.ts [hunk 11]
```diff
@@ -1,46 +1,32 @@
...
+      successCallback: () => successCallback(),
     });
-  }, [contractCallDelegateVote, token, setPending, signerOrProvider, delegatee])
-  return delegateVote;
+  }, [contractCallDelegateVote, tokenContract, delegatee, successCallback]);
+
+  return [delegateVote, contractCallPending] as const;
```
Comment (adamgall) [inline src/daoData/useDelegateVote.ts:29]: See, just return back the "pending" state coming right out of `useTransaction`

File: src/daoData/useTokenData.ts [hunk 12]
```diff
@@ -1,15 +1,16 @@
...
-import { BigNumber, ethers } from "ethers";
+import { BigNumber } from "ethers";
 
 const useTokenData = (tokenContract: VotesTokenWithSupply | undefined) => {
   const [{ account }] = useWeb3();
   const [tokenName, setTokenName] = useState<string>();
   const [tokenSymbol, setTokenSymbol] = useState<string>();
   const [tokenDecimals, setTokenDecimals] = useState<number>();
-  const [tokenBalance, setTokenBalance] = useState<number>();
+  const [tokenBalance, setTokenBalance] = useState<BigNumber>();
```
Comment (adamgall) [inline src/daoData/useTokenData.ts:11]: BigNumber > number

File: src/web3/transactions.ts [hunk 13]
```diff
@@ -28,6 +28,7 @@ const useTransaction = () => {
       closeOnClick: false,
       draggable: false,
       closeButton: false,
+      progress: 1,
```
Comment (adamgall) [inline src/web3/transactions.ts:31]: When showing a "pending transaction" toast, give it the bottom yellow bar cause it looks like (hack that yellow bar by setting `progress: 1`

**Comment by adamgall** [comment]
@tbwebb22 @christopherdancy @Da-Colon plz review at your earliest convenience

File: src/components/DAOs/DAO/Delegate.tsx (hunk 3 above)
Comment (Da-Colon) [reply src/components/DAOs/DAO/Delegate.tsx:43]: I see this `<Pending>` component in two other places in the app `Proposal/New/index.tsx` and `DAOs/New/index.tsx`. 

No need to do anything in this PR. but these also need to get replaced with Toast messages yeah?

**Review by Da-Colon — APPROVED** [review]
These changes make sense, thanks for adding the helpful comments.

File: src/components/DAOs/DAO/Delegate.tsx (hunk 3 above)
Comment (adamgall) [reply src/components/DAOs/DAO/Delegate.tsx:43]: Yes they do, see: https://github.com/fractal-framework/fractal-interface/issues/101

Comment (adamgall) [reply src/components/DAOs/DAO/Delegate.tsx:43]: i just got a jump on it here cause i was up in this component already
